Replace old links to example files
optuna/optuna-examples pull request #12
Opened 2021-05-17 08:42 UTC by nzw0301

## Motivation

I found links to `optuna/examples` that will be removed soon. 

## Description of the changes

Replace the URLs. As a result, we do not have links to files in `optuna/examples` anymore as follows.

```bash
grep  '/examples/' -r .
./allennlp/allennlp_jsonnet.py:            " https://github.com/optuna/optuna/blob/v2.5.0/examples/allennlp/allennlp_jsonnet.py"
./allennlp/allennlp_simple.py:            " https://github.com/optuna/optuna/blob/v2.5.0/examples/allennlp/allennlp_simple.py"
./haiku/haiku_simple.py:The example code is based on https://github.com/deepmind/dm-haiku/blob/master/examples/mnist.py
```

2021-05-17 08:55 UTC, nzw0301 commented
Shall we introduce the same constraint of tensorflow version as in https://github.com/optuna/optuna/pull/2674?

2021-05-18 05:10 UTC, hvy approved these changes
LGTM!

I restarted the CI builds after your fix with the TF version, but maybe we have to update this branch as well?

2021-05-18 05:10 UTC, hvy requested changes
Sorry seems so, could you sync with the latest master?

2021-05-18 05:34 UTC, nzw0301 commented
Thank you for pinging me. I have updated the branch.

2021-05-18 05:51 UTC, hvy approved these changes
Thanks, LGTM!

2021-05-18 05:51 UTC, merged